name: locomo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - openai==0.28.0
      - anthropic==0.32.0
      - google-generativeai==0.7.2
      - transformers==4.35.0
      - pandas==2.1.2
      - numpy==1.26.0
      - tqdm==4.64.1
      - pyyaml==6.0
      - jupyter
      - jupyterlab
      - spacy==3.5.1
      - nltk==3.8.1
      - sentence-transformers==2.2.2
      - bert-score==0.3.13
      - rouge==1.0.1
      - matplotlib==3.7.0
      - seaborn==0.13.0
      - fastapi==0.104.1
      - uvicorn==0.23.2
      - requests==2.31.0
      - beautifulsoup4==4.12.2
      - wandb==0.15.12
